### ISSUE TITLE
Duvida com injections

### ISSUE THREAD

**Issue by marcelokrol** [balta-io/1976#1]
Bom dia
Terminei esse seu curso, e me surgiu uma dúvida: por exemplo em um projeto grande, com várias entidades, onde desse modo será injetado via dependência, várias interfaces, essas injeções não deixará o sistema lento? Se sim, qual recurso utilizar?

**Comment by andrebaltieri** [comment]
@marcelokrol tudo que fazemos adicional, gera uso de CPU e memória, não tem jeito. Agora os containers DI que usamos normalmente resolvem milhões de objetos por segundo, então isto impacta em alguns milissegundos no startup do seu App sim, mas é pouca coisa!
